# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_src/ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 620)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../resource/OurChat_Logo_low_pixel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 54, 51))
        self.logo.setObjectName("logo")
        self.chatButton = QtWidgets.QPushButton(self.centralwidget)
        self.chatButton.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.chatButton.setObjectName("chatButton")
        self.settingButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingButton.setGeometry(QtCore.QRect(20, 570, 75, 23))
        self.settingButton.setObjectName("settingButton")
        self.CantConnectServer = QtWidgets.QLabel(self.centralwidget)
        self.CantConnectServer.setGeometry(QtCore.QRect(0, 70, 111, 16))
        self.CantConnectServer.setObjectName("CantConnectServer")
        self.chat_widget = QtWidgets.QWidget(self.centralwidget)
        self.chat_widget.setEnabled(True)
        self.chat_widget.setGeometry(QtCore.QRect(110, 0, 761, 611))
        self.chat_widget.setObjectName("chat_widget")
        self.chat_search = QtWidgets.QLineEdit(self.chat_widget)
        self.chat_search.setGeometry(QtCore.QRect(0, 0, 201, 41))
        self.chat_search.setObjectName("chat_search")
        self.chat_emojiButton = QtWidgets.QPushButton(self.chat_widget)
        self.chat_emojiButton.setGeometry(QtCore.QRect(210, 480, 21, 23))
        self.chat_emojiButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../resource/test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_emojiButton.setIcon(icon1)
        self.chat_emojiButton.setIconSize(QtCore.QSize(32, 32))
        self.chat_emojiButton.setObjectName("chat_emojiButton")
        self.chat_input = QtWidgets.QTextEdit(self.chat_widget)
        self.chat_input.setGeometry(QtCore.QRect(200, 510, 561, 91))
        self.chat_input.setObjectName("chat_input")
        self.chat_brower = QtWidgets.QTextBrowser(self.chat_widget)
        self.chat_brower.setGeometry(QtCore.QRect(200, 60, 561, 421))
        self.chat_brower.setObjectName("chat_brower")
        self.chat_chats = QtWidgets.QScrollArea(self.chat_widget)
        self.chat_chats.setEnabled(True)
        self.chat_chats.setGeometry(QtCore.QRect(0, 40, 200, 560))
        self.chat_chats.setWidgetResizable(False)
        self.chat_chats.setObjectName("chat_chats")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 180, 561))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.chat_chats.setWidget(self.scrollAreaWidgetContents)
        self.chat_imageButton = QtWidgets.QPushButton(self.chat_widget)
        self.chat_imageButton.setGeometry(QtCore.QRect(240, 480, 21, 23))
        self.chat_imageButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../resource/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_imageButton.setIcon(icon2)
        self.chat_imageButton.setIconSize(QtCore.QSize(16, 32))
        self.chat_imageButton.setObjectName("chat_imageButton")
        self.chat_send = QtWidgets.QPushButton(self.chat_widget)
        self.chat_send.setGeometry(QtCore.QRect(680, 570, 75, 23))
        self.chat_send.setObjectName("chat_send")
        self.chat_fileButton = QtWidgets.QPushButton(self.chat_widget)
        self.chat_fileButton.setGeometry(QtCore.QRect(270, 480, 21, 23))
        self.chat_fileButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../resource/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_fileButton.setIcon(icon3)
        self.chat_fileButton.setIconSize(QtCore.QSize(16, 32))
        self.chat_fileButton.setObjectName("chat_fileButton")
        self.chat_name = QtWidgets.QLabel(self.chat_widget)
        self.chat_name.setGeometry(QtCore.QRect(200, 0, 561, 61))
        self.chat_name.setObjectName("chat_name")
        self.setting_widget = QtWidgets.QWidget(self.centralwidget)
        self.setting_widget.setEnabled(True)
        self.setting_widget.setGeometry(QtCore.QRect(110, 0, 771, 611))
        self.setting_widget.setObjectName("setting_widget")
        self.setting_Logo = QtWidgets.QLabel(self.setting_widget)
        self.setting_Logo.setGeometry(QtCore.QRect(290, 10, 221, 221))
        self.setting_Logo.setObjectName("setting_Logo")
        self.setting_serverIp = QtWidgets.QLineEdit(self.setting_widget)
        self.setting_serverIp.setGeometry(QtCore.QRect(310, 240, 211, 31))
        self.setting_serverIp.setObjectName("setting_serverIp")
        self.setting_server_ip_text = QtWidgets.QLabel(self.setting_widget)
        self.setting_server_ip_text.setGeometry(QtCore.QRect(240, 250, 54, 12))
        self.setting_server_ip_text.setObjectName("setting_server_ip_text")
        self.setting_lang = QtWidgets.QComboBox(self.setting_widget)
        self.setting_lang.setGeometry(QtCore.QRect(310, 300, 211, 31))
        self.setting_lang.setObjectName("setting_lang")
        self.setting_lang_text = QtWidgets.QLabel(self.setting_widget)
        self.setting_lang_text.setGeometry(QtCore.QRect(240, 310, 54, 12))
        self.setting_lang_text.setObjectName("setting_lang_text")
        self.setting_clearCache = QtWidgets.QPushButton(self.setting_widget)
        self.setting_clearCache.setGeometry(QtCore.QRect(340, 380, 75, 23))
        self.setting_clearCache.setObjectName("setting_clearCache")
        self.setting_logout = QtWidgets.QPushButton(self.setting_widget)
        self.setting_logout.setGeometry(QtCore.QRect(340, 430, 75, 23))
        self.setting_logout.setObjectName("setting_logout")
        self.login_widget = QtWidgets.QWidget(self.centralwidget)
        self.login_widget.setGeometry(QtCore.QRect(0, 0, 460, 550))
        self.login_widget.setObjectName("login_widget")
        self.login_startImg = QtWidgets.QLabel(self.login_widget)
        self.login_startImg.setGeometry(QtCore.QRect(0, 0, 460, 150))
        self.login_startImg.setObjectName("login_startImg")
        self.login_account = QtWidgets.QLineEdit(self.login_widget)
        self.login_account.setGeometry(QtCore.QRect(120, 180, 221, 31))
        self.login_account.setObjectName("login_account")
        self.login_password = QtWidgets.QLineEdit(self.login_widget)
        self.login_password.setGeometry(QtCore.QRect(120, 240, 221, 31))
        self.login_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.login_password.setObjectName("login_password")
        self.login_login = QtWidgets.QPushButton(self.login_widget)
        self.login_login.setGeometry(QtCore.QRect(190, 310, 75, 23))
        self.login_login.setObjectName("login_login")
        self.login_showPassword = QtWidgets.QCheckBox(self.login_widget)
        self.login_showPassword.setGeometry(QtCore.QRect(260, 290, 91, 16))
        self.login_showPassword.setObjectName("login_showPassword")
        self.login_more = QtWidgets.QToolButton(self.login_widget)
        self.login_more.setGeometry(QtCore.QRect(420, 330, 37, 18))
        self.login_more.setObjectName("login_more")
        self.login_tip = QtWidgets.QLabel(self.login_widget)
        self.login_tip.setGeometry(QtCore.QRect(120, 270, 221, 21))
        self.login_tip.setObjectName("login_tip")
        self.login_another = QtWidgets.QCommandLinkButton(self.login_widget)
        self.login_another.setGeometry(QtCore.QRect(79, 500, 321, 40))
        self.login_another.setObjectName("login_another")
        self.login_serverIp = QtWidgets.QLineEdit(self.login_widget)
        self.login_serverIp.setGeometry(QtCore.QRect(120, 370, 210, 30))
        self.login_serverIp.setObjectName("login_serverIp")
        self.login_lang = QtWidgets.QComboBox(self.login_widget)
        self.login_lang.setGeometry(QtCore.QRect(120, 430, 210, 30))
        self.login_lang.setObjectName("login_lang")
        self.login_lang_text = QtWidgets.QLabel(self.login_widget)
        self.login_lang_text.setGeometry(QtCore.QRect(70, 440, 41, 16))
        self.login_lang_text.setObjectName("login_lang_text")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OurChat"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/新前缀/OurChat/resource/OurChat_Logo_low_pixel.png\"/></p></body></html>"))
        self.chatButton.setText(_translate("MainWindow", "聊天"))
        self.settingButton.setText(_translate("MainWindow", "设置"))
        self.CantConnectServer.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#ff0000;\">无法连接至服务器</span></p></body></html>"))
        self.chat_send.setText(_translate("MainWindow", "发送"))
        self.chat_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">ChatName</span></p></body></html>"))
        self.setting_Logo.setText(_translate("MainWindow", "<html><head/><body><img src=\"../../resource/OurChat_logo.png\"></body></html>"))
        self.setting_serverIp.setPlaceholderText(_translate("MainWindow", "服务器IP"))
        self.setting_server_ip_text.setText(_translate("MainWindow", "服务器IP"))
        self.setting_lang_text.setText(_translate("MainWindow", "语言"))
        self.setting_clearCache.setText(_translate("MainWindow", "清空缓存"))
        self.setting_logout.setText(_translate("MainWindow", "退出登录"))
        self.login_startImg.setText(_translate("MainWindow", "<html><head/><body><img src=\"../../resource/startImg.png\" /></body></html>"))
        self.login_account.setPlaceholderText(_translate("MainWindow", "账号/邮箱"))
        self.login_password.setPlaceholderText(_translate("MainWindow", "密码"))
        self.login_login.setText(_translate("MainWindow", "登录"))
        self.login_showPassword.setText(_translate("MainWindow", "显示密码"))
        self.login_more.setText(_translate("MainWindow", "更多"))
        self.login_tip.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" color:#ff0000;\">哼哼哼啊啊啊啊啊啊啊啊啊啊啊啊啊啊</span></p></body></html>"))
        self.login_another.setText(_translate("MainWindow", "CommandLinkButton"))
        self.login_serverIp.setPlaceholderText(_translate("MainWindow", "服务器IP"))
        self.login_lang_text.setText(_translate("MainWindow", "语言"))
