# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_src/ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../resource/OurChat_Logo_low_pixel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(20, 10, 54, 51))
        self.logo.setObjectName("logo")
        self.chatButton = QtWidgets.QPushButton(self.centralwidget)
        self.chatButton.setGeometry(QtCore.QRect(10, 100, 75, 23))
        self.chatButton.setObjectName("chatButton")
        self.settingButton = QtWidgets.QPushButton(self.centralwidget)
        self.settingButton.setGeometry(QtCore.QRect(20, 570, 75, 23))
        self.settingButton.setObjectName("settingButton")
        self.chat_chats = QtWidgets.QScrollArea(self.centralwidget)
        self.chat_chats.setGeometry(QtCore.QRect(110, 40, 200, 560))
        self.chat_chats.setWidgetResizable(False)
        self.chat_chats.setObjectName("chat_chats")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 180, 561))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        '''self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 181, 51))
        self.pushButton.setObjectName("pushButton")'''
        self.chat_chats.setWidget(self.scrollAreaWidgetContents)
        self.chat_name = QtWidgets.QLabel(self.centralwidget)
        self.chat_name.setGeometry(QtCore.QRect(310, 0, 561, 61))
        self.chat_name.setObjectName("chat_name")
        self.chat_brower = QtWidgets.QTextBrowser(self.centralwidget)
        self.chat_brower.setGeometry(QtCore.QRect(310, 60, 561, 421))
        self.chat_brower.setObjectName("chat_brower")
        self.chat_input = QtWidgets.QTextEdit(self.centralwidget)
        self.chat_input.setGeometry(QtCore.QRect(310, 510, 561, 91))
        self.chat_input.setObjectName("chat_input")
        self.chat_emojiButton = QtWidgets.QPushButton(self.centralwidget)
        self.chat_emojiButton.setGeometry(QtCore.QRect(320, 480, 21, 23))
        self.chat_emojiButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../resource/test.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_emojiButton.setIcon(icon1)
        self.chat_emojiButton.setIconSize(QtCore.QSize(32, 32))
        self.chat_emojiButton.setObjectName("chat_emojiButton")
        self.chat_imageButton = QtWidgets.QPushButton(self.centralwidget)
        self.chat_imageButton.setGeometry(QtCore.QRect(350, 480, 21, 23))
        self.chat_imageButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../resource/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_imageButton.setIcon(icon2)
        self.chat_imageButton.setIconSize(QtCore.QSize(16, 32))
        self.chat_imageButton.setObjectName("chat_imageButton")
        self.chat_send = QtWidgets.QPushButton(self.centralwidget)
        self.chat_send.setGeometry(QtCore.QRect(790, 570, 75, 23))
        self.chat_send.setObjectName("chat_send")
        self.setting_logo = QtWidgets.QLabel(self.centralwidget)
        self.setting_logo.setGeometry(QtCore.QRect(460, 0, 211, 191))
        self.setting_logo.setObjectName("setting_logo")
        self.setting_clearCache = QtWidgets.QPushButton(self.centralwidget)
        self.setting_clearCache.setGeometry(QtCore.QRect(540, 300, 75, 23))
        self.setting_clearCache.setObjectName("setting_clearCache")
        self.chat_search = QtWidgets.QLineEdit(self.centralwidget)
        self.chat_search.setGeometry(QtCore.QRect(110, 0, 201, 41))
        self.chat_search.setObjectName("chat_search")
        self.setting_serverIp = QtWidgets.QLineEdit(self.centralwidget)
        self.setting_serverIp.setGeometry(QtCore.QRect(560, 230, 113, 20))
        self.setting_serverIp.setObjectName("setting_serverIp")
        self.setting_text = QtWidgets.QLabel(self.centralwidget)
        self.setting_text.setGeometry(QtCore.QRect(490, 230, 54, 12))
        self.setting_text.setObjectName("setting_text")
        self.setting_toGithub = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.setting_toGithub.setGeometry(QtCore.QRect(430, 380, 311, 71))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../resource/github.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_toGithub.setIcon(icon3)
        self.setting_toGithub.setObjectName("setting_toGithub")
        self.CantConnectServer = QtWidgets.QLabel(self.centralwidget)
        self.CantConnectServer.setGeometry(QtCore.QRect(0, 70, 111, 16))
        self.CantConnectServer.setObjectName("CantConnectServer")
        self.tips = QtWidgets.QLabel(self.centralwidget)
        self.tips.setGeometry(QtCore.QRect(110, 559, 671, 41))
        self.tips.setObjectName("tips")
        self.chat_fileButton = QtWidgets.QPushButton(self.centralwidget)
        self.chat_fileButton.setGeometry(QtCore.QRect(380, 480, 21, 23))
        self.chat_fileButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../resource/file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_fileButton.setIcon(icon4)
        self.chat_fileButton.setIconSize(QtCore.QSize(16, 32))
        self.chat_fileButton.setObjectName("chat_fileButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OurChat"))
        self.logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/新前缀/OurChat/resource/OurChat_Logo_low_pixel.png\"/></p></body></html>"))
        self.chatButton.setText(_translate("MainWindow", "聊天"))
        self.settingButton.setText(_translate("MainWindow", "设置"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.chat_name.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">ChatName</span></p></body></html>"))
        self.chat_send.setText(_translate("MainWindow", "发送"))
        self.setting_logo.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/新前缀/OurChat/resource/OurChat_logo.png\"/></p></body></html>"))
        self.setting_clearCache.setText(_translate("MainWindow", "清空缓存"))
        self.setting_text.setText(_translate("MainWindow", "服务器IP"))
        self.setting_toGithub.setText(_translate("MainWindow", "Github地址"))
        self.CantConnectServer.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">无法连接至服务器</span></p></body></html>"))
        self.tips.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">This is tip</span></p></body></html>"))
