from logging import DEBUG, INFO, WARNING, CRITICAL, ERROR

# Message
USER_MSG = 0
REGISTER_MSG = 4
REGISTER_RESPONSE_MSG = 5
LOGIN_MSG = 6
LOGIN_RESPONSE_MSG = 7
NEW_SESSION_MSG = 8
NEW_SESSION_RESPONSE_MSG = 9
ACCOUNT_INFO_MSG = 10
ACCOUNT_INFO_RESPONSE_MSG = 11
SERVER_STATUS_MSG = 12
INIT_VERIFY_MSG = 13
GENERATE_VERIFY_MSG = 14
VERIFY_STATUS_MSG = 15

# Log Level
log_level2str = {
    DEBUG: "DEBUG",
    INFO: "INFO",
    WARNING: "WARNING",
    CRITICAL: "CRITICAL",
    ERROR: "ERROR",
}
str2log_level = {
    "DEBUG": DEBUG,
    "INFO": INFO,
    "WARNING": WARNING,
    "CRITICAL": CRITICAL,
    "ERROR": ERROR,
}
