from logging import CRITICAL, DEBUG, ERROR, INFO, WARNING

# Message
USER_MSG = 0
SESSION_INFO_MSG = 1
SESSION_INFO_RESPONSE_MSG = 2
REGISTER_MSG = 4
REGISTER_RESPONSE_MSG = 5
LOGIN_MSG = 6
LOGIN_RESPONSE_MSG = 7
NEW_SESSION_MSG = 8
NEW_SESSION_RESPONSE_MSG = 9
ACCOUNT_INFO_MSG = 10
ACCOUNT_INFO_RESPONSE_MSG = 11
SERVER_STATUS_MSG = 12
INIT_VERIFY_MSG = 13
GENERATE_VERIFY_MSG = 14
VERIFY_STATUS_MSG = 15
UNREGISTER_MSG = 16
UNREGISTER_RESPONSE_MSG = 17
ERROR_MSG = 18
SET_ACCOUNT_INFO_MSG = 19
SET_ACCOUNT_INFO_RESPONSE_MSG = 20
UPLOAD_MSG = 21
UPLOAD_RESPONSE_MSG = 22

# Log Level
log_level2str = {
    DEBUG: "DEBUG",
    INFO: "INFO",
    WARNING: "WARNING",
    CRITICAL: "CRITICAL",
    ERROR: "ERROR",
}
str2log_level = {
    "DEBUG": DEBUG,
    "INFO": INFO,
    "WARNING": WARNING,
    "CRITICAL": CRITICAL,
    "ERROR": ERROR,
}

# Client Event
ACCOUNT_FINISH_GET_INFO = -1
ACCOUNT_FINISH_GET_AVATAR = -2
SESSION_FINISH_GET_INFO = -3
SESSION_FINISH_GET_AVATAR = -4
CONNECT_TO_SERVER_RESPONSE = -5
DOWNLOAD_RESPONSE = -6
UPLOAD_RESPONSE = -7

# User Msg
USER_MSG_TEXT = 0

# STATUS CODE
RUN_NORMALLY = 0
SERVER_ERROR = 1
SERVER_UNDER_MAINTENANCE = 2
REQUEST_INFO_NOT_FOUND = 3
NEW_INFO_EXIST = 4
ARGUMENT_ERROR = 5
ACCOUNT_LIMIT = 6
TIMEOUT = 7
UNKNOWN_ERROR = 8

# HTTP CODE
HTTP_OK = 200
