# The http server listening ip
ip = "0.0.0.0"
# The http server listening port
port = 7777
redis_cfg = "redis.toml"
db_cfg = "database.toml"
user_setting = "user_setting.toml"
# If not set, the email will be disabled
email_cfg = "email.toml"
rabbitmq_cfg = "rabbitmq.toml"
# The logo of this server
logo_path = "/root/resource/logo.png"
default_avatar_path = "/root/resource/logo.png"
verification_html_template_path = "/root/resource/email.html"
run_migration = false
# enable Matrix Api
enable_matrix = false

# control rate limit
[rate_limit]
# Enable rate limit
enable = true
# The maximum number of requests allowed per duration from a single IP address
num_of_burst_requests = 8
# replenish one request every duration seconds
replenish_duration = "500ms"

[tls]
# Enable tls encryption
enable = false
client_certificate_required = false
# The address of the tsl certificate, if not specified, the tls will be disabled
# server_tls_cert_path = ""
# server_key_cert_path = ""
# client_tls_cert_path = ""
# client_key_cert_path = ""
# ca_tls_cert_path = ""
# client_ca_tls_cert_path = ""
