# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/account.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_Account(object):
    def setupUi(self, Account):
        Account.setObjectName("Account")
        Account.resize(400, 300)
        Account.setWindowTitle("Form")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Account)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(
            134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.avatar_label = QtWidgets.QLabel(Account)
        self.avatar_label.setText("Avatar")
        self.avatar_label.setObjectName("avatar_label")
        self.horizontalLayout.addWidget(self.avatar_label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.nickname_label = QtWidgets.QLabel(Account)
        self.nickname_label.setText("NickName")
        self.nickname_label.setObjectName("nickname_label")
        self.verticalLayout.addWidget(self.nickname_label)
        self.ocid_label = QtWidgets.QLabel(Account)
        self.ocid_label.setText("OCID")
        self.ocid_label.setObjectName("ocid_label")
        self.verticalLayout.addWidget(self.ocid_label)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.logout_btn = QtWidgets.QPushButton(Account)
        self.logout_btn.setText("Logout")
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_2.addWidget(self.logout_btn)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(
            134, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem3)

        self.retranslateUi(Account)
        QtCore.QMetaObject.connectSlotsByName(Account)

    def retranslateUi(self, Account):
        pass
