//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "metrics_history")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    pub timestamp: DateTimeWithTimeZone,
    pub active_connections: i32,
    pub total_users: i32,
    #[sea_orm(column_type = "Double")]
    pub messages_per_second: f64,
    pub uptime_seconds: i64,
    #[sea_orm(column_type = "Double", nullable)]
    pub cpu_usage_percent: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub memory_usage_percent: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub disk_usage_percent: Option<f64>,
    pub total_sessions: i32,
    pub active_sessions: i32,
    pub database_connections: i32,
    pub rabbitmq_connections: i32,
    pub created_at: DateTimeWithTimeZone,
    pub tokio_workers_count: Option<i32>,
    pub tokio_total_park_count: Option<i64>,
    pub tokio_max_park_count: Option<i64>,
    pub tokio_min_park_count: Option<i64>,
    pub tokio_total_busy_duration: Option<i64>,
    pub tokio_max_busy_duration: Option<i64>,
    pub tokio_min_busy_duration: Option<i64>,
    pub tokio_global_queue_depth: Option<i64>,
    pub tokio_elapsed: Option<i64>,
    pub tokio_live_tasks_count: Option<i64>,
    pub tokio_mean_poll_duration: Option<i64>,
    pub tokio_mean_poll_duration_worker_min: Option<i64>,
    pub tokio_mean_poll_duration_worker_max: Option<i64>,
    pub tokio_total_noop_count: Option<i64>,
    pub tokio_max_noop_count: Option<i64>,
    pub tokio_min_noop_count: Option<i64>,
    pub tokio_total_steal_count: Option<i64>,
    pub tokio_max_steal_count: Option<i64>,
    pub tokio_min_steal_count: Option<i64>,
    pub tokio_total_steal_operations: Option<i64>,
    pub tokio_max_steal_operations: Option<i64>,
    pub tokio_min_steal_operations: Option<i64>,
    pub tokio_num_remote_schedules: Option<i64>,
    pub tokio_total_local_schedule_count: Option<i64>,
    pub tokio_max_local_schedule_count: Option<i64>,
    pub tokio_min_local_schedule_count: Option<i64>,
    pub tokio_total_overflow_count: Option<i64>,
    pub tokio_max_overflow_count: Option<i64>,
    pub tokio_min_overflow_count: Option<i64>,
    pub tokio_total_polls_count: Option<i64>,
    pub tokio_max_polls_count: Option<i64>,
    pub tokio_min_polls_count: Option<i64>,
    pub tokio_total_local_queue_depth: Option<i64>,
    pub tokio_max_local_queue_depth: Option<i64>,
    pub tokio_min_local_queue_depth: Option<i64>,
    pub tokio_blocking_queue_depth: Option<i64>,
    pub tokio_blocking_threads_count: Option<i64>,
    pub tokio_idle_blocking_threads_count: Option<i64>,
    pub tokio_budget_forced_yield_count: Option<i64>,
    pub tokio_io_driver_ready_count: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tokio_busy_ratio: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tokio_mean_polls_per_park: Option<f64>,
    pub tokio_task_instrumented_count: Option<i64>,
    pub tokio_task_dropped_count: Option<i64>,
    pub tokio_task_first_poll_count: Option<i64>,
    pub tokio_task_total_first_poll_delay: Option<i64>,
    pub tokio_task_total_idled_count: Option<i64>,
    pub tokio_task_total_idle_duration: Option<i64>,
    pub tokio_task_max_idle_duration: Option<i64>,
    pub tokio_task_total_scheduled_count: Option<i64>,
    pub tokio_task_total_scheduled_duration: Option<i64>,
    pub tokio_task_total_poll_count: Option<i64>,
    pub tokio_task_total_poll_duration: Option<i64>,
    pub tokio_task_total_fast_poll_count: Option<i64>,
    pub tokio_task_total_fast_poll_duration: Option<i64>,
    pub tokio_task_total_slow_poll_count: Option<i64>,
    pub tokio_task_total_slow_poll_duration: Option<i64>,
    pub tokio_task_total_short_delay_count: Option<i64>,
    pub tokio_task_total_short_delay_duration: Option<i64>,
    pub tokio_task_total_long_delay_count: Option<i64>,
    pub tokio_task_total_long_delay_duration: Option<i64>,
    pub tokio_task_mean_first_poll_delay: Option<i64>,
    pub tokio_task_mean_idle_duration: Option<i64>,
    pub tokio_task_mean_scheduled_duration: Option<i64>,
    pub tokio_task_mean_poll_duration: Option<i64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tokio_task_slow_poll_ratio: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub tokio_task_long_delay_ratio: Option<f64>,
    pub tokio_task_mean_fast_poll_duration: Option<i64>,
    pub tokio_task_mean_slow_poll_duration: Option<i64>,
    pub tokio_task_mean_short_delay_duration: Option<i64>,
    pub tokio_task_mean_long_delay_duration: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
