//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod authority;
pub mod files;
pub mod friend;
pub mod permission;
pub mod role;
pub mod role_permissions;
pub mod server_manager;
pub mod session;
pub mod session_relation;
pub mod user;
pub mod user_chat_msg;
pub mod user_role_relation;
