//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod announcement;
pub mod announcement_msg;
pub mod files;
pub mod friend;
pub mod manager_role_relation;
pub mod message_records;
pub mod permission;
pub mod role;
pub mod role_permissions;
pub mod rtc_room;
pub mod server_management_permission;
pub mod server_management_role;
pub mod server_management_role_permissions;
pub mod session;
pub mod session_invitation;
pub mod session_relation;
pub mod user;
pub mod user_contact_info;
pub mod user_role_relation;
pub mod user_status;
pub mod webrtc_room;
pub mod webrtc_room_member;
