//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub use super::authority::Entity as Authority;
pub use super::files::Entity as Files;
pub use super::friend::Entity as Friend;
pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::role_permissions::Entity as RolePermissions;
pub use super::server_manager::Entity as ServerManager;
pub use super::session::Entity as Session;
pub use super::session_relation::Entity as SessionRelation;
pub use super::user::Entity as User;
pub use super::user_chat_msg::Entity as UserChatMsg;
pub use super::user_contact_info::Entity as UserContactInfo;
pub use super::user_role_relation::Entity as UserRoleRelation;
