//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recall_votes")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub msg_id: i64,
    pub session_id: i64,
    pub initiator_id: i64,
    pub yes_count: i64,
    pub no_count: i64,
    pub eligible_count: i64,
    pub deadline: DateTimeWithTimeZone,
    pub settled: bool,
    pub passed: bool,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recall_vote_records::Entity")]
    RecallVoteRecords,
    #[sea_orm(
        belongs_to = "super::session::Entity",
        from = "Column::SessionId",
        to = "super::session::Column::SessionId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Session,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::InitiatorId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::recall_vote_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecallVoteRecords.def()
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Session.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::recall_vote_records::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::recall_vote_records::Relation::RecallVotes
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
