//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "recall_vote_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub vote_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i64,
    pub approve: bool,
    pub voted_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::recall_votes::Entity",
        from = "Column::VoteId",
        to = "super::recall_votes::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    RecallVotes,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::recall_votes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecallVotes.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
