//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "server_management_role_permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub permission_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::server_management_permission::Entity",
        from = "Column::PermissionId",
        to = "super::server_management_permission::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ServerManagementPermission,
    #[sea_orm(
        belongs_to = "super::server_management_role::Entity",
        from = "Column::RoleId",
        to = "super::server_management_role::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ServerManagementRole,
}

impl Related<super::server_management_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServerManagementPermission.def()
    }
}

impl Related<super::server_management_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ServerManagementRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
