//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(unique)]
    pub ocid: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub passwd: Option<String>,
    pub name: String,
    #[sea_orm(unique)]
    pub email: String,
    pub time: DateTimeWithTimeZone,
    pub resource_used: i64,
    pub friend_limit: i32,
    pub friends_num: i32,
    pub avatar: Option<String>,
    pub account_status: i32,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub public_key: Vec<u8>,
    #[sea_orm(unique)]
    pub github_id: Option<String>,
    pub oauth_provider: Option<String>,
    pub email_verified: bool,
    pub public_update_time: DateTimeWithTimeZone,
    pub update_time: DateTimeWithTimeZone,
    pub email_visible: bool,
    pub session_invitation_policy: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::announcement::Entity")]
    Announcement,
    #[sea_orm(has_many = "super::files::Entity")]
    Files,
    #[sea_orm(has_one = "super::manager_role_relation::Entity")]
    ManagerRoleRelation,
    #[sea_orm(has_many = "super::message_records::Entity")]
    MessageRecords,
    #[sea_orm(has_many = "super::recall_vote_records::Entity")]
    RecallVoteRecords,
    #[sea_orm(has_many = "super::recall_votes::Entity")]
    RecallVotes,
    #[sea_orm(has_many = "super::role::Entity")]
    Role,
    #[sea_orm(has_many = "super::session_relation::Entity")]
    SessionRelation,
    #[sea_orm(has_many = "super::stickers::Entity")]
    Stickers,
    #[sea_orm(has_many = "super::user_role_relation::Entity")]
    UserRoleRelation,
    #[sea_orm(has_many = "super::webrtc_room_member::Entity")]
    WebrtcRoomMember,
}

impl Related<super::announcement::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Announcement.def()
    }
}

impl Related<super::manager_role_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ManagerRoleRelation.def()
    }
}

impl Related<super::message_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageRecords.def()
    }
}

impl Related<super::recall_vote_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecallVoteRecords.def()
    }
}

impl Related<super::role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Role.def()
    }
}

impl Related<super::session_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionRelation.def()
    }
}

impl Related<super::stickers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Stickers.def()
    }
}

impl Related<super::user_role_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRoleRelation.def()
    }
}

impl Related<super::webrtc_room_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebrtcRoomMember.def()
    }
}

impl Related<super::files::Entity> for Entity {
    fn to() -> RelationDef {
        super::stickers::Relation::Files.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::stickers::Relation::User.def().rev())
    }
}

impl Related<super::recall_votes::Entity> for Entity {
    fn to() -> RelationDef {
        super::recall_vote_records::Relation::RecallVotes.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::recall_vote_records::Relation::User.def().rev())
    }
}

impl Related<super::session::Entity> for Entity {
    fn to() -> RelationDef {
        super::session_relation::Relation::Session.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::session_relation::Relation::User.def().rev())
    }
}

impl Related<super::webrtc_room::Entity> for Entity {
    fn to() -> RelationDef {
        super::webrtc_room_member::Relation::WebrtcRoom.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::webrtc_room_member::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
