//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "webrtc_room")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: Option<String>,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::webrtc_room_member::Entity")]
    WebrtcRoomMember,
}

impl Related<super::webrtc_room_member::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebrtcRoomMember.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
