//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "webrtc_room_member")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub room_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i64,
    pub name: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::webrtc_room::Entity",
        from = "Column::RoomId",
        to = "super::webrtc_room::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    WebrtcRoom,
}

impl Related<super::webrtc_room::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WebrtcRoom.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
