//! Logging host implementation
//!
//! Provides logging functionality to plugins via the WIT logging interface.

use crate::engine::PluginState;
use parking_lot::RwLock;
use std::sync::Arc;

/// Host implementation for the logging interface
pub struct LoggingHost {
    state: Arc<RwLock<PluginState>>,
}

impl LoggingHost {
    pub fn new(state: Arc<RwLock<PluginState>>) -> Self {
        Self { state }
    }

    fn plugin_id(&self) -> String {
        self.state.read().plugin_id.clone()
    }
}

/// Implement the logging interface from WIT
/// Note: This is a placeholder - the actual trait implementation
/// will be generated by wit-bindgen from the WIT definitions

impl LoggingHost {
    pub fn trace(&mut self, msg: String) {
        tracing::trace!(plugin = %self.plugin_id(), "{}", msg);
    }

    pub fn debug(&mut self, msg: String) {
        tracing::debug!(plugin = %self.plugin_id(), "{}", msg);
    }

    pub fn info(&mut self, msg: String) {
        tracing::info!(plugin = %self.plugin_id(), "{}", msg);
    }

    pub fn warn(&mut self, msg: String) {
        tracing::warn!(plugin = %self.plugin_id(), "{}", msg);
    }

    pub fn error(&mut self, msg: String) {
        tracing::error!(plugin = %self.plugin_id(), "{}", msg);
    }
}
