FROM skyuoi/ourchat:aphine-base AS chef

# We only pay the installation cost once, 
# it will be cached from the second build onwards
RUN cargo install cargo-chef 
WORKDIR /app

FROM chef AS planner

COPY . .
RUN cargo chef prepare  --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /app/recipe.json recipe.json
RUN cargo chef cook --tests --recipe-path recipe.json
COPY . .
CMD [ "cd", "/app","&&", "cargo", "test" ]
