FROM rustlang/rust:nightly AS builder

WORKDIR /app

RUN apt update && apt install protobuf-compiler cmake -y

COPY . .

RUN cd /app/server && cargo build --release

FROM debian:stable-slim

COPY --from=builder /app/target/release/server /usr/local/bin/server
COPY --from=builder /app/config /etc/ourchat

CMD ["server", "-c", "/etc/ourchat/ourchat.toml"]
