# Form implementation generated from reading ui file '.\login.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(330, 210)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Login)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=Login)
        self.tabWidget.setObjectName("tabWidget")
        self.login_tab = QtWidgets.QWidget()
        self.login_tab.setObjectName("login_tab")
        self.formLayout = QtWidgets.QFormLayout(self.login_tab)
        self.formLayout.setObjectName("formLayout")
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.formLayout.setItem(0, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)
        self.ocid_email_label = QtWidgets.QLabel(parent=self.login_tab)
        self.ocid_email_label.setText("OCID/Email")
        self.ocid_email_label.setObjectName("ocid_email_label")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.ocid_email_label
        )
        self.login_account_editor = QtWidgets.QLineEdit(parent=self.login_tab)
        self.login_account_editor.setObjectName("login_account_editor")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.login_account_editor
        )
        self.login_password_label = QtWidgets.QLabel(parent=self.login_tab)
        self.login_password_label.setText("Password")
        self.login_password_label.setObjectName("login_password_label")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.login_password_label
        )
        self.login_password_editor = QtWidgets.QLineEdit(parent=self.login_tab)
        self.login_password_editor.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.login_password_editor.setObjectName("login_password_editor")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.login_password_editor
        )
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem1)
        self.login_show_checkbox = QtWidgets.QCheckBox(parent=self.login_tab)
        self.login_show_checkbox.setText("Show")
        self.login_show_checkbox.setObjectName("login_show_checkbox")
        self.horizontalLayout.addWidget(self.login_show_checkbox)
        self.formLayout.setLayout(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout
        )
        spacerItem2 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.formLayout.setItem(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem2
        )
        self.tabWidget.addTab(self.login_tab, "Login")
        self.register_tab = QtWidgets.QWidget()
        self.register_tab.setObjectName("register_tab")
        self.formLayout_2 = QtWidgets.QFormLayout(self.register_tab)
        self.formLayout_2.setObjectName("formLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.formLayout_2.setItem(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem3
        )
        self.email_label = QtWidgets.QLabel(parent=self.register_tab)
        self.email_label.setText("Email")
        self.email_label.setObjectName("email_label")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.email_label
        )
        self.register_email_editor = QtWidgets.QLineEdit(parent=self.register_tab)
        self.register_email_editor.setObjectName("register_email_editor")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.register_email_editor
        )
        self.register_password_label = QtWidgets.QLabel(parent=self.register_tab)
        self.register_password_label.setText("Password")
        self.register_password_label.setObjectName("register_password_label")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.register_password_label
        )
        self.register_password_editor = QtWidgets.QLineEdit(parent=self.register_tab)
        self.register_password_editor.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.register_password_editor.setObjectName("register_password_editor")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.register_password_editor
        )
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_2.addItem(spacerItem4)
        self.register_show_checkbox = QtWidgets.QCheckBox(parent=self.register_tab)
        self.register_show_checkbox.setText("Show")
        self.register_show_checkbox.setObjectName("register_show_checkbox")
        self.horizontalLayout_2.addWidget(self.register_show_checkbox)
        self.formLayout_2.setLayout(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_2
        )
        spacerItem5 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.formLayout_2.setItem(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem5
        )
        self.tabWidget.addTab(self.register_tab, "Register")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.setting_btn = QtWidgets.QPushButton(parent=Login)
        self.setting_btn.setObjectName("setting_btn")
        self.horizontalLayout_6.addWidget(self.setting_btn)
        spacerItem6 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_6.addItem(spacerItem6)
        self.join_btn = QtWidgets.QPushButton(parent=Login)
        self.join_btn.setText("Join")
        self.join_btn.setObjectName("join_btn")
        self.horizontalLayout_6.addWidget(self.join_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Login)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.setting_btn.setText(_translate("Login", "Setting"))
