# Form implementation generated from reading ui file '.\sessionSetting.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class Ui_SessionSetting(object):
    def setupUi(self, SessionSetting):
        SessionSetting.setObjectName("SessionSetting")
        SessionSetting.resize(400, 300)
        SessionSetting.setWindowTitle("Dialog")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(SessionSetting)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.avatar_label = QtWidgets.QLabel(parent=SessionSetting)
        self.avatar_label.setText("Avatar")
        self.avatar_label.setObjectName("avatar_label")
        self.verticalLayout.addWidget(self.avatar_label)
        self.set_avatar_btn = QtWidgets.QPushButton(parent=SessionSetting)
        self.set_avatar_btn.setText("Set")
        self.set_avatar_btn.setObjectName("set_avatar_btn")
        self.verticalLayout.addWidget(self.set_avatar_btn)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(parent=SessionSetting)
        self.label_2.setText("Name")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.session_name_editor = QtWidgets.QLineEdit(parent=SessionSetting)
        self.session_name_editor.setObjectName("session_name_editor")
        self.horizontalLayout_5.addWidget(self.session_name_editor)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.member_box = QtWidgets.QGroupBox(parent=SessionSetting)
        self.member_box.setObjectName("member_box")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.member_box)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.member_list = QtWidgets.QListWidget(parent=self.member_box)
        self.member_list.setObjectName("member_list")
        self.horizontalLayout_3.addWidget(self.member_list)
        self.verticalLayout_2.addWidget(self.member_box)
        self.verticalLayout_2.setStretch(0, 3)
        self.verticalLayout_2.setStretch(1, 5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(
            20,
            40,
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.horizontalLayout.addItem(spacerItem4)
        self.ok_btn = QtWidgets.QPushButton(parent=SessionSetting)
        self.ok_btn.setText("OK")
        self.ok_btn.setObjectName("ok_btn")
        self.horizontalLayout.addWidget(self.ok_btn)
        self.cancel_btn = QtWidgets.QPushButton(parent=SessionSetting)
        self.cancel_btn.setText("Cancel")
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(SessionSetting)
        QtCore.QMetaObject.connectSlotsByName(SessionSetting)

    def retranslateUi(self, SessionSetting):
        _translate = QtCore.QCoreApplication.translate
        self.member_box.setTitle(_translate("SessionSetting", "Members"))
