//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "session")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub session_id: i64,
    pub name: String,
    pub size: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::session_relation::Entity")]
    SessionRelation,
    #[sea_orm(has_many = "super::user_chat_msg::Entity")]
    UserChatMsg,
}

impl Related<super::session_relation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionRelation.def()
    }
}

impl Related<super::user_chat_msg::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserChatMsg.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
