inherit = "../docker/config/http.toml"
# The http server listening ip
ip = "localhost"
logo_path = "../resource/logo.png"
default_avatar_path = "../resource/logo.png"
verification_html_template_path = "../resource/email.html"
