//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod authority;
pub mod files;
pub mod friend;
pub mod operations;
pub mod server_manager;
pub mod session;
pub mod session_relation;
pub mod user;
pub mod user_chat_msg;
pub mod user_chat_msg_relation;
