//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_chat_msg_relation")]
pub struct Model {
    pub user_id: i64,
    #[sea_orm(primary_key, auto_increment = false)]
    pub chat_msg_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    User,
    #[sea_orm(
        belongs_to = "super::user_chat_msg::Entity",
        from = "Column::ChatMsgId",
        to = "super::user_chat_msg::Column::ChatMsgId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    UserChatMsg,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::user_chat_msg::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserChatMsg.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
