//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::chat::Entity as Chat;
pub use super::chat_group::Entity as ChatGroup;
pub use super::friend::Entity as Friend;
pub use super::user::Entity as User;
pub use super::user_chat_id::Entity as UserChatId;
pub use super::user_chat_msg::Entity as UserChatMsg;
