//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_chat_id")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub chat_msg_id: u32,
    pub msg_type: Option<i32>,
    pub msg_data: Option<String>,
    pub sender_id: Option<u64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
